Allow to modify 'name' during the version creation if obj already exists
whole-tale/wt_versioning pull request #18
Opened 2021-02-08 20:37 UTC by Xarthisius

If `?allowRename=True` is passed to `POST /version` and the `name` is already used, a magical `(n)` will be appended to it, ensuring that the version name is unique. In every other situation the behavior is unchanged, i.e. `_checkName` should raise 409.

2021-02-09 19:47 UTC, bodom0015 commented
New parameter fixes the Create case :+1:
Unfortunately, the Rename/Update case still has the same issue.

Would it be controversial to add this parameter/behavior to the PUT endpoint as well?
Or would it be preferable to leave the Rename case using the modal and risk an edge case race condition?

2021-02-09 20:32 UTC, Xarthisius commented
Race condition? Rename should be instantaneous

2021-02-11 17:27 UTC, bodom0015 approved these changes
I feel like we've discussed this race condition at length: https://github.com/whole-tale/ngx-dashboard/issues/117

The race condition happens when we call `/version/exists` in the UI - if the user submits before this call returns, then they effectively bypass the form validation and get an error popup about a 409. This PR fixes the "Create" case by preventing a conflict from ever occurring.

I went ahead and added the necessary handling in the UI to fix this behavior for the "Update" case - the "Save" button is now disabled with a loading indicator as we validate the version name. A valid (unique) name enables the button, whereas an invalid name keeps the button disabled and prevents submission without modification

Noting that the "Create" case uses Option 2 presented in the issue above, where "Update" now uses Option 1. If we prefer one behavior over the other throughout, then we should consolidate.

See related PR for more info: https://github.com/whole-tale/ngx-dashboard/pull/138

2021-02-15 17:18 UTC, bodom0015 commented
Sorry for the confusion, but I missed the commit where you added the `allowRename` behavior to the `PUT` endpoint. We can discuss at the meeting this afternoon :+1:

2021-02-17 15:06 UTC, bodom0015 requested changes
With the latest changes, both endpoints no longer works and throw an error.

Testing in Swagger UI (without the dashboard), I am getting the following:

## Create with `allowRename=True`
Creating any Tale version, even with valid inputs, throws the following error.

Request: https://girder.local.wholetale.org/api/v1/version?taleId=602aa004fe9716257de765ae&name=Iveneverusedthisnamebefore&force=true&allowRename=true

Response:
```json
{
  "message": "KeyError: KeyError('dataSet')",
  "trace": [
    "<FrameSummary file /girder/girder/api/rest.py, line 630 in endpointDecorator>",
    "<FrameSummary file /girder/girder/api/rest.py, line 1224 in POST>",
    "<FrameSummary file /girder/girder/api/rest.py, line 967 in handleRoute>",
    "<FrameSummary file /girder/girder/api/access.py, line 63 in wrapped>",
    "<FrameSummary file /girder/girder/api/rest.py, line 445 in wrapped>",
    "<FrameSummary file /girder/girder/api/describe.py, line 709 in wrapped>",
    "<FrameSummary file /girder/plugins/wt_versioning/server/resources/version.py, line 131 in create>",
    "<FrameSummary file /girder/plugins/wt_versioning/server/resources/version.py, line 241 in _create>"
  ],
  "type": "internal"
}
```

## Rename with `allowRename=True`
Attempting to rename a Tale using `allowRename=True` yields the following error.

Request: https://girder.local.wholetale.org/api/v1/version/602aa186fe9716257de765b9?name=version%203&allowRename=true

Response: 
```json
{
  "field": "name",
  "message": "A folder with that name already exists here.",
  "type": "validation"
}
```

2021-02-17 15:26 UTC, Xarthisius commented
@bodom0015 there's been no changes to this plugin's master, nor new commits in this PR in past 8 days.
My hunch is that you've tested https://github.com/whole-tale/wt_versioning/pull/15, during which you're created a version of Tale. Then you switched back to this PR and tried to create another version of that tale.
Anyways, remove the Tale, create a new one and check if issue persists.

2021-02-17 17:25 UTC, bodom0015 commented
You are correct for the Create case - sorry for not noticing that this was just a bad Tale state.

In the Rename case, I am still getting this back when sending `allowRename=True`:
```json
{"field": "name", "message": "A folder with that name already exists here.", "type": "validation"}
```

2021-02-17 18:32 UTC, Xarthisius commented
> In the Rename case, I am still getting this back when sending `allowRename=True`:

Oops, missing assignment... Should be fixed now.

2021-02-19 20:30 UTC, merged